"""3D viewport widget embedding pygfx in PySide6 via rendercanvas.

Renders point clouds with PointsGaussianBlobMaterial for soft Gaussian
blob particles. Provides orbit/zoom/pan via OrbitController.

Supports progressive point cloud building (one cloud per photo),
layout mode switching, multi-photo stacking/merging, and integrated
simulation engine with FPS counter overlay.
"""

from __future__ import annotations

import logging

import numpy as np
from PySide6 import QtCore, QtWidgets
from rendercanvas.qt import QRenderWidget
import pygfx as gfx

from apollo7.config.settings import (
    BG_COLOR_BOTTOM,
    BG_COLOR_TOP,
    OPACITY_DEFAULT,
    POINT_SIZE_DEFAULT,
)
from apollo7.gui.widgets.fps_counter import FPSCounter
from apollo7.postfx.bloom import BloomController
from apollo7.postfx.dof_pass import DepthOfFieldPass
from apollo7.postfx.ssao_pass import SSAOPass
from apollo7.postfx.trails import TrailAccumulator
from apollo7.rendering.camera import CameraController
from apollo7.rendering.crossfade import CrossfadeEngine
from apollo7.simulation.parameters import SimulationParams

logger = logging.getLogger(__name__)

# Additive blending validation (RENDER-03):
# pygfx PointsGaussianBlobMaterial does NOT expose a blend_mode parameter.
# Workaround: alpha < 1.0 combined with Gaussian blob falloff.
BLEND_MODE_AVAILABLE: bool = False
_BLEND_ALPHA: float = 0.85

# Signal emitted when layout regeneration is needed (connected by MainWindow)
_LAYOUT_CHANGE_SIGNAL_NAME = "layout_change_requested"


class ViewportWidget(QtWidgets.QWidget):
    """PySide6 widget containing a pygfx 3D viewport.

    Supports progressive point cloud building with per-photo cloud
    management, layout mode switching, real-time material updates,
    and integrated simulation engine with FPS counter.
    """

    # Emitted when layout mode or multi-photo mode changes and clouds
    # need to be regenerated by the main window
    layout_change_requested = QtCore.Signal()

    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QtWidgets.QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)

        # Embedded render canvas
        self._canvas = QRenderWidget(self, update_mode="continuous")
        layout.addWidget(self._canvas)

        # pygfx core objects
        self._renderer = gfx.WgpuRenderer(self._canvas)
        self._scene = gfx.Scene()
        self._camera = gfx.PerspectiveCamera(60)

        # Dark gradient background
        self._scene.add(gfx.Background.from_color(BG_COLOR_TOP, BG_COLOR_BOTTOM))

        # Camera controller (orbit/zoom/pan)
        self._camera_controller = CameraController(
            self._camera, self._renderer
        )

        # Per-photo point cloud tracking: {photo_id: gfx.Points}
        self._photo_clouds: dict[str, gfx.Points] = {}

        # Legacy list for backward compat
        self._point_objects: list[gfx.Points] = []

        # Current material parameters
        self._current_point_size: float = POINT_SIZE_DEFAULT
        self._current_opacity: float = OPACITY_DEFAULT

        # Layout / multi-photo mode
        self._layout_mode: str = "depth_projected"
        self._multi_photo_mode: str = "stacked"

        # Post-processing effects (None until init_postfx is called)
        self._bloom: BloomController | None = None
        self._dof: DepthOfFieldPass | None = None
        self._ssao: SSAOPass | None = None
        self._trails: TrailAccumulator | None = None

        # Simulation engine (None until Simulate is clicked)
        self._sim_engine = None
        self._sim_cloud: gfx.Points | None = None  # merged cloud driven by sim

        # GPU buffer sharing (None until sim initialized)
        self._shared_pos_buf: gfx.Buffer | None = None
        self._shared_color_buf: gfx.Buffer | None = None
        self._gpu_sharing_active: bool = False

        # Crossfade engine for smooth parameter transitions
        self._crossfade = CrossfadeEngine(self._apply_crossfaded_param)

        # Embedding cloud manager (None until collection analysis runs)
        self._embedding_cloud_manager = None

        # FPS counter overlay
        self._fps_counter = FPSCounter(self)
        self._fps_counter.raise_()

        # Log blending approach
        if BLEND_MODE_AVAILABLE:
            logger.info("Blending: additive via blend_mode")
        else:
            logger.info(
                "Blending: soft overlap via alpha falloff workaround "
                f"(alpha={_BLEND_ALPHA})"
            )

        # Start render loop (no test points -- real data comes from extraction)
        self._canvas.request_draw(self._animate)

    def resizeEvent(self, event):
        """Reposition FPS counter on resize."""
        super().resizeEvent(event)
        # Top-right corner with 8px margin
        w = self._fps_counter.width()
        self._fps_counter.move(self.width() - w - 8, 8)

    def _animate(self):
        """Called each frame to render the scene."""
        self._fps_counter.tick()
        if self._sim_engine and self._sim_engine.running and not self._sim_engine.paused:
            self._sim_engine.step()
            self._update_points_from_sim()
        self._renderer.render(self._scene, self._camera)

    # ------------------------------------------------------------------
    # Per-photo cloud management
    # ------------------------------------------------------------------

    def add_photo_cloud(
        self,
        photo_id: str,
        positions: np.ndarray,
        colors: np.ndarray,
        sizes: np.ndarray,
        layer_index: int = 0,
    ) -> gfx.Points:
        """Add a point cloud to the scene tagged with a photo_id.

        For stacked layers mode, a Z-offset based on layer_index is
        applied. The cloud replaces any existing cloud for the same
        photo_id.

        Args:
            photo_id: Unique identifier (usually photo path).
            positions: (N, 3) float32 array of XYZ positions.
            colors: (N, 4) float32 array of RGBA colors.
            sizes: (N,) float32 array of per-point sizes.
            layer_index: Layer index for Z-offset in stacked mode.

        Returns:
            The created gfx.Points object.
        """
        # Remove existing cloud for this photo if any
        self.remove_photo_cloud(photo_id)

        # Apply current opacity to colors
        colors = colors.copy()
        colors[:, 3] = np.minimum(colors[:, 3], self._current_opacity)

        # Apply current point size
        sizes = sizes.copy()
        size_ratio = self._current_point_size / POINT_SIZE_DEFAULT
        sizes *= size_ratio

        points_obj = self.add_points(positions, colors, sizes)
        self._photo_clouds[photo_id] = points_obj

        # Auto-frame after adding each photo cloud
        self.auto_frame()

        return points_obj

    def remove_photo_cloud(self, photo_id: str) -> None:
        """Remove a specific photo's point cloud from the scene."""
        if photo_id in self._photo_clouds:
            pts = self._photo_clouds.pop(photo_id)
            self._scene.remove(pts)
            if pts in self._point_objects:
                self._point_objects.remove(pts)

    def set_layout_mode(self, mode: str) -> None:
        """Switch between 'depth_projected' and 'feature_clustered'.

        Clears all clouds and emits layout_change_requested so the main
        window can regenerate them.
        """
        if mode == self._layout_mode:
            return
        self._layout_mode = mode
        self.clear_all_photo_clouds()
        self.layout_change_requested.emit()

    def set_multi_photo_mode(self, mode: str) -> None:
        """Switch between 'stacked' and 'merged' multi-photo modes.

        Clears all clouds and emits layout_change_requested so the main
        window can regenerate them.
        """
        if mode == self._multi_photo_mode:
            return
        self._multi_photo_mode = mode
        self.clear_all_photo_clouds()
        self.layout_change_requested.emit()

    def update_point_material(
        self,
        point_size: float | None = None,
        opacity: float | None = None,
    ) -> None:
        """Update material properties on all point objects in the scene.

        Args:
            point_size: New point size (applied as size multiplier).
            opacity: New opacity for all points.
        """
        if point_size is not None:
            self._current_point_size = point_size
        if opacity is not None:
            self._current_opacity = opacity

        for pts in self._point_objects:
            geo = pts.geometry
            if point_size is not None and geo.sizes is not None:
                current_sizes = geo.sizes.data
                size_ratio = point_size / POINT_SIZE_DEFAULT
                new_sizes = np.full_like(current_sizes, POINT_SIZE_DEFAULT * size_ratio)
                geo.sizes = gfx.Buffer(new_sizes.astype(np.float32))
            if opacity is not None and geo.colors is not None:
                new_colors = geo.colors.data.copy()
                new_colors[:, 3] = opacity
                geo.colors = gfx.Buffer(new_colors.astype(np.float32))

    def clear_all_photo_clouds(self) -> None:
        """Remove all photo-tagged clouds from the scene."""
        for photo_id in list(self._photo_clouds.keys()):
            self.remove_photo_cloud(photo_id)

    @property
    def layout_mode(self) -> str:
        return self._layout_mode

    @property
    def multi_photo_mode(self) -> str:
        return self._multi_photo_mode

    # ------------------------------------------------------------------
    # Low-level point cloud API (from Plan 01)
    # ------------------------------------------------------------------

    def add_points(
        self,
        positions: np.ndarray,
        colors: np.ndarray,
        sizes: np.ndarray,
    ) -> gfx.Points:
        """Add a point cloud to the scene.

        Args:
            positions: (N, 3) float32 array of XYZ positions.
            colors: (N, 4) float32 array of RGBA colors.
            sizes: (N,) float32 array of per-point sizes.

        Returns:
            The created gfx.Points object.
        """
        # Apply blend alpha for luminous overlap effect on white background
        colors = colors.copy().astype(np.float32)
        colors[:, 3] = np.minimum(colors[:, 3], _BLEND_ALPHA)

        geometry = gfx.Geometry(
            positions=positions.astype(np.float32),
            colors=colors,
            sizes=sizes.astype(np.float32),
        )
        material = gfx.PointsGaussianBlobMaterial(
            color_mode="vertex",
            size_mode="vertex",
        )
        points = gfx.Points(geometry, material)
        self._scene.add(points)
        self._point_objects.append(points)
        return points

    def clear_points(self):
        """Remove all point cloud objects from the scene."""
        for pts in self._point_objects:
            self._scene.remove(pts)
        self._point_objects.clear()
        self._photo_clouds.clear()

    def auto_frame(self):
        """Position camera to show the entire scene with three-quarter view."""
        if not self._point_objects:
            return  # Nothing to frame — skip to avoid bounding sphere error
        try:
            self._camera.show_object(self._scene)
        except ValueError:
            # Scene has no bounding sphere — fall back to manual framing
            pass
        self._camera_controller.set_three_quarter_view()

    def reset_camera(self):
        """Reset camera to default position framing the scene."""
        self.auto_frame()

    # ------------------------------------------------------------------
    # Post-processing effects
    # ------------------------------------------------------------------

    def init_postfx(self) -> None:
        """Initialize all post-processing effects.

        Creates BloomController (attached to renderer), DoF, SSAO, and
        TrailAccumulator instances. Bloom is enabled by default; others
        are disabled until toggled on via the PostFX panel.
        """
        try:
            self._bloom = BloomController(self._renderer)
            logger.info("Bloom post-fx initialized")
        except Exception as exc:
            logger.warning("Failed to initialize bloom: %s", exc)
            self._bloom = None

        self._dof = DepthOfFieldPass()
        self._ssao = SSAOPass()
        self._trails = TrailAccumulator()

        logger.info("Post-processing effects initialized")

    def update_postfx_param(self, name: str, value: float) -> None:
        """Update a post-processing parameter by name.

        Args:
            name: Parameter name (e.g. 'bloom_strength', 'dof_focal_distance').
            value: New parameter value.
        """
        if name == "bloom_strength" and self._bloom is not None:
            self._bloom.set_strength(value)
        elif name == "dof_focal_distance" and self._dof is not None:
            self._dof.focal_distance = value
        elif name == "dof_aperture" and self._dof is not None:
            self._dof.aperture = value
        elif name == "ssao_radius" and self._ssao is not None:
            self._ssao.radius = value
        elif name == "ssao_intensity" and self._ssao is not None:
            self._ssao.intensity = value
        elif name == "trail_length" and self._trails is not None:
            self._trails.trail_length = value
        else:
            logger.debug("Unknown postfx param: %s", name)

    def toggle_postfx(self, effect: str, enabled: bool) -> None:
        """Toggle a post-processing effect on/off.

        Args:
            effect: Effect name ('bloom', 'dof', 'ssao', 'trails').
            enabled: Whether the effect should be enabled.
        """
        if effect == "bloom" and self._bloom is not None:
            self._bloom.set_enabled(enabled)
        elif effect == "dof" and self._dof is not None:
            self._dof.enabled = enabled
        elif effect == "ssao" and self._ssao is not None:
            self._ssao.enabled = enabled
        elif effect == "trails" and self._trails is not None:
            self._trails.enabled = enabled
        else:
            logger.debug("Unknown postfx effect: %s", effect)

    # ------------------------------------------------------------------
    # Simulation engine integration
    # ------------------------------------------------------------------

    def _cleanup_sim_cloud(self) -> None:
        """Remove the previous sim cloud and restore photo cloud visibility."""
        if self._sim_cloud is not None:
            self._scene.remove(self._sim_cloud)
            if self._sim_cloud in self._point_objects:
                self._point_objects.remove(self._sim_cloud)
            self._sim_cloud = None
        # Clean up shared GPU buffers
        self._shared_pos_buf = None
        self._shared_color_buf = None
        self._gpu_sharing_active = False
        # Restore photo cloud visibility
        for pts in self._photo_clouds.values():
            pts.visible = True

    def init_simulation(
        self,
        positions: np.ndarray,
        colors: np.ndarray,
        feature_textures: dict[str, np.ndarray] | None = None,
    ) -> None:
        """Initialize the simulation engine with point cloud data.

        Creates a SimulationEngine using the renderer's wgpu device,
        uploads initial state, and prepares compute pipelines.
        Hides individual photo clouds and creates a single merged sim cloud.

        Args:
            positions: (N, 3) float32 array of XYZ positions.
            colors: (N, 4) float32 array of RGBA colors.
            feature_textures: Optional dict with "edge_map" and/or "depth_map".
        """
        from apollo7.simulation.engine import SimulationEngine

        # Clean up any previous sim cloud
        self._cleanup_sim_cloud()

        # Hide individual photo clouds — sim cloud replaces them visually
        for pts in self._photo_clouds.values():
            pts.visible = False

        # Create a single merged sim cloud
        sizes = np.full(len(positions), self._current_point_size, dtype=np.float32)
        self._sim_cloud = self.add_points(positions.astype(np.float32), colors.astype(np.float32), sizes)

        device = self._renderer.device
        self._sim_engine = SimulationEngine(device)
        self._sim_engine.initialize(positions, colors, feature_textures)

        # Set up GPU buffer sharing for zero-copy rendering
        self._setup_gpu_buffer_sharing(len(positions))
        logger.info("Simulation initialized with %d particles", positions.shape[0])

    def start_simulation(self) -> None:
        """Start the simulation (engine must be initialized first)."""
        if self._sim_engine is None:
            logger.warning("Cannot start simulation: engine not initialized")
            return
        if not self._sim_engine.running:
            self._sim_engine.restart()
        logger.info("Simulation started")

    def pause_simulation(self) -> None:
        """Pause the running simulation."""
        if self._sim_engine:
            self._sim_engine.pause()

    def resume_simulation(self) -> None:
        """Resume the paused simulation."""
        if self._sim_engine:
            self._sim_engine.resume()

    def toggle_pause(self) -> None:
        """Toggle between paused and running simulation states."""
        if self._sim_engine:
            self._sim_engine.toggle_pause()

    def update_sim_param(self, name: str, value: float) -> None:
        """Route a parameter update through the crossfade engine.

        Continuous params get smooth ease-out transitions (~0.4s).
        Discrete params (solver_iterations) snap instantly.

        Args:
            name: Parameter name from SimulationParams.
            value: New parameter value.
        """
        if self._sim_engine is None:
            return

        # Get current value for interpolation start point
        current = self._get_current_param_value(name)
        self._crossfade.set_target(name, value, current)

    def _get_current_param_value(self, name: str) -> float:
        """Get current value of a simulation parameter for crossfade start.

        Args:
            name: Parameter name.

        Returns:
            Current float value of the parameter.
        """
        if self._sim_engine is None:
            return 0.0

        params = self._sim_engine.params
        # Handle compound params
        if name == "gravity_y":
            return params.gravity[1]
        elif name == "wind_x":
            return params.wind[0]
        elif name == "wind_z":
            return params.wind[2]
        elif hasattr(params, name):
            val = getattr(params, name)
            return float(val) if not isinstance(val, tuple) else 0.0
        return 0.0

    def _apply_crossfaded_param(self, name: str, value: float) -> None:
        """Apply an interpolated parameter value from the crossfade engine.

        Routes the value to the appropriate target: simulation engine,
        point material, bloom controller, etc.

        Args:
            name: Parameter name.
            value: Interpolated value from CrossfadeEngine.
        """
        if name == "point_size":
            self.update_point_material(point_size=value)
        elif name == "opacity":
            self.update_point_material(opacity=value)
        elif name == "bloom_strength" and self._bloom is not None:
            self._bloom.set_strength(value)
        elif self._sim_engine is not None:
            # Route to simulation engine
            if name == "gravity_y":
                current = self._sim_engine.params.gravity
                self._sim_engine.update_visual_param(
                    "gravity", (current[0], value, current[2])
                )
            elif name == "wind_x":
                current = self._sim_engine.params.wind
                self._sim_engine.update_visual_param(
                    "wind", (value, current[1], current[2])
                )
            elif name == "wind_z":
                current = self._sim_engine.params.wind
                self._sim_engine.update_visual_param(
                    "wind", (current[0], current[1], value)
                )
            elif SimulationParams.is_visual_param(name):
                self._sim_engine.update_visual_param(name, value)
            elif SimulationParams.is_physics_param(name):
                self._sim_engine.update_physics_param(name, value)
            else:
                logger.debug("Unknown crossfade param: %s", name)

    def apply_crossfaded_preset(self, preset_dict: dict) -> None:
        """Apply a preset dict through the crossfade engine for smooth transitions.

        Each key in the preset is routed through CrossfadeEngine.set_target
        for ease-out interpolation, replacing instant preset snapping with
        smooth chase animation.

        Args:
            preset_dict: Dict of {param_name: value} from PresetPanel crossfade.
        """
        for name, value in preset_dict.items():
            try:
                current = self._get_current_param_value(name)
                self._crossfade.set_target(name, float(value), current)
            except (TypeError, ValueError):
                logger.debug("Skipping non-numeric preset param: %s", name)

    def _setup_gpu_buffer_sharing(self, n_particles: int) -> None:
        """Set up GPU buffer sharing between simulation and pygfx.

        NOTE: Direct _wgpu_object injection is incompatible with pygfx's
        internal vertex shaders (expects vec3 positions, we have vec4).
        Currently disabled — uses CPU readback fallback instead.
        GPU buffer sharing needs a different approach (e.g., custom render
        pipeline or pygfx format negotiation) for future optimization.

        Args:
            n_particles: Number of particles for buffer sizing.
        """
        # Disabled: pygfx vertex shader expects vec3 positions but our
        # render_positions_buffer stores vec4. Injecting causes shader
        # validation error. Fall back to CPU readback for now.
        self._gpu_sharing_active = False
        logger.info(
            "GPU buffer sharing disabled (pygfx vec3/vec4 mismatch), "
            "using CPU readback for %d particles",
            n_particles,
        )

    def _update_points_from_sim(self) -> None:
        """Update pygfx geometry from simulation GPU buffers.

        Primary path: GPU buffer sharing via extract_positions compute shader.
        Fallback: CPU readback + re-upload (prototype compatibility).
        """
        if self._sim_engine is None or self._sim_cloud is None:
            return

        if self._gpu_sharing_active:
            try:
                # Dispatch extract-positions shader (GPU -> GPU, no readback)
                pb = self._sim_engine._particle_buffer
                pb.extract_positions_to_render(self._sim_engine._device)

                # Tell pygfx the buffer content changed (triggers re-render)
                if self._shared_pos_buf is not None:
                    self._shared_pos_buf.update_range(0, 0)
                return
            except Exception as exc:
                logger.warning(
                    "GPU buffer sharing failed, falling back to CPU readback: %s",
                    exc,
                )
                self._gpu_sharing_active = False

        # Fallback: CPU readback path
        try:
            positions = self._sim_engine._particle_buffer.read_positions()
            geo = self._sim_cloud.geometry
            geo.positions = gfx.Buffer(positions.astype(np.float32))
        except Exception as exc:
            logger.debug("Failed to update points from sim: %s", exc)

    # ------------------------------------------------------------------
    # Embedding cloud integration
    # ------------------------------------------------------------------

    def update_embedding_cloud(self, result) -> None:
        """Update the embedding cloud visualization with new analysis results.

        Creates an EmbeddingCloudManager if one doesn't exist yet.

        Args:
            result: CollectionResult from CollectionAnalyzer.analyze().
        """
        from apollo7.collection.embedding_cloud import EmbeddingCloudManager

        if self._embedding_cloud_manager is None:
            self._embedding_cloud_manager = EmbeddingCloudManager(self)

        self._embedding_cloud_manager.update(result)

    def toggle_embedding_cloud(self) -> None:
        """Toggle visibility of the embedding cloud overlay."""
        if self._embedding_cloud_manager is not None:
            self._embedding_cloud_manager.toggle_visibility()

    def handle_embedding_click(self, cluster_id: int, result) -> None:
        """Handle click on an embedding cloud point.

        First click on a cluster isolates it (dims others).
        Second click on the same cluster or any click when isolated
        clears the isolation.

        Args:
            cluster_id: Cluster ID of the clicked point.
            result: CollectionResult for path lookup.
        """
        if self._embedding_cloud_manager is None:
            return

        mgr = self._embedding_cloud_manager
        if mgr.isolated_cluster == cluster_id:
            # Same cluster clicked again -- clear isolation
            mgr.clear_isolation()
        elif mgr.isolated_cluster is not None:
            # Different cluster -- switch isolation
            mgr.clear_isolation()
            if cluster_id >= 0:
                mgr.isolate_cluster(cluster_id, result)
        else:
            # No isolation active -- isolate clicked cluster
            if cluster_id >= 0:
                mgr.isolate_cluster(cluster_id, result)

    @property
    def embedding_cloud_manager(self):
        """Access the EmbeddingCloudManager instance, if any."""
        return self._embedding_cloud_manager
