"""3D viewport widget embedding pygfx in PySide6 via rendercanvas.

Renders point clouds with PointsGaussianBlobMaterial for soft Gaussian
blob particles. Provides orbit/zoom/pan via OrbitController.

Supports progressive point cloud building (one cloud per photo),
layout mode switching, and multi-photo stacking/merging.
"""

from __future__ import annotations

import logging

import numpy as np
from PySide6 import QtCore, QtWidgets
from rendercanvas.qt import QRenderWidget
import pygfx as gfx

from apollo7.config.settings import (
    BG_COLOR_BOTTOM,
    BG_COLOR_TOP,
    OPACITY_DEFAULT,
    POINT_SIZE_DEFAULT,
)
from apollo7.rendering.camera import CameraController

logger = logging.getLogger(__name__)

# Additive blending validation (RENDER-03):
# pygfx PointsGaussianBlobMaterial does NOT expose a blend_mode parameter.
# Workaround: alpha < 1.0 combined with Gaussian blob falloff.
BLEND_MODE_AVAILABLE: bool = False
_BLEND_ALPHA: float = 0.7

# Signal emitted when layout regeneration is needed (connected by MainWindow)
_LAYOUT_CHANGE_SIGNAL_NAME = "layout_change_requested"


class ViewportWidget(QtWidgets.QWidget):
    """PySide6 widget containing a pygfx 3D viewport.

    Supports progressive point cloud building with per-photo cloud
    management, layout mode switching, and real-time material updates.
    """

    # Emitted when layout mode or multi-photo mode changes and clouds
    # need to be regenerated by the main window
    layout_change_requested = QtCore.Signal()

    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QtWidgets.QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)

        # Embedded render canvas
        self._canvas = QRenderWidget(self, update_mode="continuous")
        layout.addWidget(self._canvas)

        # pygfx core objects
        self._renderer = gfx.WgpuRenderer(self._canvas)
        self._scene = gfx.Scene()
        self._camera = gfx.PerspectiveCamera(60)

        # Dark gradient background
        self._scene.add(gfx.Background.from_color(BG_COLOR_TOP, BG_COLOR_BOTTOM))

        # Camera controller (orbit/zoom/pan)
        self._camera_controller = CameraController(
            self._camera, self._renderer
        )

        # Per-photo point cloud tracking: {photo_id: gfx.Points}
        self._photo_clouds: dict[str, gfx.Points] = {}

        # Legacy list for backward compat
        self._point_objects: list[gfx.Points] = []

        # Current material parameters
        self._current_point_size: float = POINT_SIZE_DEFAULT
        self._current_opacity: float = OPACITY_DEFAULT

        # Layout / multi-photo mode
        self._layout_mode: str = "depth_projected"
        self._multi_photo_mode: str = "stacked"

        # Log blending approach
        if BLEND_MODE_AVAILABLE:
            logger.info("Blending: additive via blend_mode")
        else:
            logger.info(
                "Blending: soft overlap via alpha falloff workaround "
                f"(alpha={_BLEND_ALPHA})"
            )

        # Start render loop (no test points -- real data comes from extraction)
        self._canvas.request_draw(self._animate)

    def _animate(self):
        """Called each frame to render the scene."""
        self._renderer.render(self._scene, self._camera)

    # ------------------------------------------------------------------
    # Per-photo cloud management
    # ------------------------------------------------------------------

    def add_photo_cloud(
        self,
        photo_id: str,
        positions: np.ndarray,
        colors: np.ndarray,
        sizes: np.ndarray,
        layer_index: int = 0,
    ) -> gfx.Points:
        """Add a point cloud to the scene tagged with a photo_id.

        For stacked layers mode, a Z-offset based on layer_index is
        applied. The cloud replaces any existing cloud for the same
        photo_id.

        Args:
            photo_id: Unique identifier (usually photo path).
            positions: (N, 3) float32 array of XYZ positions.
            colors: (N, 4) float32 array of RGBA colors.
            sizes: (N,) float32 array of per-point sizes.
            layer_index: Layer index for Z-offset in stacked mode.

        Returns:
            The created gfx.Points object.
        """
        # Remove existing cloud for this photo if any
        self.remove_photo_cloud(photo_id)

        # Apply current opacity to colors
        colors = colors.copy()
        colors[:, 3] = np.minimum(colors[:, 3], self._current_opacity)

        # Apply current point size
        sizes = sizes.copy()
        size_ratio = self._current_point_size / POINT_SIZE_DEFAULT
        sizes *= size_ratio

        points_obj = self.add_points(positions, colors, sizes)
        self._photo_clouds[photo_id] = points_obj

        # Auto-frame after adding each photo cloud
        self.auto_frame()

        return points_obj

    def remove_photo_cloud(self, photo_id: str) -> None:
        """Remove a specific photo's point cloud from the scene."""
        if photo_id in self._photo_clouds:
            pts = self._photo_clouds.pop(photo_id)
            self._scene.remove(pts)
            if pts in self._point_objects:
                self._point_objects.remove(pts)

    def set_layout_mode(self, mode: str) -> None:
        """Switch between 'depth_projected' and 'feature_clustered'.

        Clears all clouds and emits layout_change_requested so the main
        window can regenerate them.
        """
        if mode == self._layout_mode:
            return
        self._layout_mode = mode
        self.clear_all_photo_clouds()
        self.layout_change_requested.emit()

    def set_multi_photo_mode(self, mode: str) -> None:
        """Switch between 'stacked' and 'merged' multi-photo modes.

        Clears all clouds and emits layout_change_requested so the main
        window can regenerate them.
        """
        if mode == self._multi_photo_mode:
            return
        self._multi_photo_mode = mode
        self.clear_all_photo_clouds()
        self.layout_change_requested.emit()

    def update_point_material(
        self,
        point_size: float | None = None,
        opacity: float | None = None,
    ) -> None:
        """Update material properties on all point objects in the scene.

        Args:
            point_size: New point size (applied as size multiplier).
            opacity: New opacity for all points.
        """
        if point_size is not None:
            self._current_point_size = point_size
        if opacity is not None:
            self._current_opacity = opacity

        for pts in self._point_objects:
            geo = pts.geometry
            if point_size is not None and geo.sizes is not None:
                current_sizes = geo.sizes.data
                size_ratio = point_size / POINT_SIZE_DEFAULT
                new_sizes = np.full_like(current_sizes, POINT_SIZE_DEFAULT * size_ratio)
                geo.sizes = gfx.Buffer(new_sizes.astype(np.float32))
            if opacity is not None and geo.colors is not None:
                new_colors = geo.colors.data.copy()
                new_colors[:, 3] = opacity
                geo.colors = gfx.Buffer(new_colors.astype(np.float32))

    def clear_all_photo_clouds(self) -> None:
        """Remove all photo-tagged clouds from the scene."""
        for photo_id in list(self._photo_clouds.keys()):
            self.remove_photo_cloud(photo_id)

    @property
    def layout_mode(self) -> str:
        return self._layout_mode

    @property
    def multi_photo_mode(self) -> str:
        return self._multi_photo_mode

    # ------------------------------------------------------------------
    # Low-level point cloud API (from Plan 01)
    # ------------------------------------------------------------------

    def add_points(
        self,
        positions: np.ndarray,
        colors: np.ndarray,
        sizes: np.ndarray,
    ) -> gfx.Points:
        """Add a point cloud to the scene.

        Args:
            positions: (N, 3) float32 array of XYZ positions.
            colors: (N, 4) float32 array of RGBA colors.
            sizes: (N,) float32 array of per-point sizes.

        Returns:
            The created gfx.Points object.
        """
        geometry = gfx.Geometry(
            positions=positions.astype(np.float32),
            colors=colors.astype(np.float32),
            sizes=sizes.astype(np.float32),
        )
        material = gfx.PointsGaussianBlobMaterial(
            color_mode="vertex",
            size_mode="vertex",
        )
        points = gfx.Points(geometry, material)
        self._scene.add(points)
        self._point_objects.append(points)
        return points

    def clear_points(self):
        """Remove all point cloud objects from the scene."""
        for pts in self._point_objects:
            self._scene.remove(pts)
        self._point_objects.clear()
        self._photo_clouds.clear()

    def auto_frame(self):
        """Position camera to show the entire scene with three-quarter view."""
        if not self._point_objects:
            return  # Nothing to frame — skip to avoid bounding sphere error
        try:
            self._camera.show_object(self._scene)
        except ValueError:
            # Scene has no bounding sphere — fall back to manual framing
            pass
        self._camera_controller.set_three_quarter_view()
